server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: api-gateway

app-config:
  jwt:
    expiration: 600000
  secrets:
    api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=DHUASU12H3HOPA=sada2hih213hAhAS2IHahiHU2UHuihashuHU2U1HIUhhashas812378HH231U2I}