server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: auth-api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://localhost:5432/course-auth-db?createDatabaseIfNotExist=true
    username: postgres
    password: 12345

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  config:
    jwt:
      expiration: 600000
    secrets:
      api-secret: ${API_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=DHUASU12H3HOPA=sada2hih213hAhAS2IHahiHU2UHuihashuHU2U1HIUhhashas812378HH231U2I}

    rabbit:
      exchange:
        email: email.topic
      routing-key:
        student-registered: student-registered.routingKey
      queue:
        student-registered: student-registered.queue