server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost

spring:
  application:
    name: email-service

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: '**usernameDaAplicaçãoSMTPdoGmail**'
    password: '**SenhaDaSuaAplicaçãoSMTPdoGmail**'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  config:
    rabbit:
      exchange:
        email: email.topic
      routing-key:
        student-registered: student-registered.routingKey
      queue:
        student-registered: student-registered.queue
